#!/usr/bin/env python3
"""Generate deterministic publication figures and LaTeX tables.

The script reads only frozen repository inputs. It does not rerun GBBRPM,
retrieve remote data, or alter source results.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import networkx as nx
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = ROOT / "results" / "paper"
FIGURE_DIR = OUTPUT_ROOT / "figures"
TABLE_DIR = OUTPUT_ROOT / "tables"

BLUE = "#2563EB"
NAVY = "#1F2937"
GREEN = "#059669"
AMBER = "#D97706"
RED = "#DC2626"
SLATE = "#64748B"
LIGHT = "#CBD5E1"
PALE = "#E2E8F0"

NETWORKS = ["N1", "N2", "N3", "N4", "N5"]
NETWORK_COLORS = {
    "N1": "#17365D",
    "N2": "#B24A3B",
    "N3": "#6F8F3D",
    "N4": "#76538D",
    "N5": "#2F8FA8",
}
NETWORK_MARKERS = {"N1": "o", "N2": "s", "N3": "^", "N4": "D", "N5": "v"}


def configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 8,
            "axes.labelsize": 8,
            "axes.titlesize": 9,
            "legend.fontsize": 7,
            "xtick.labelsize": 7,
            "ytick.labelsize": 7,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.edgecolor": SLATE,
            "axes.linewidth": 0.7,
            "grid.color": PALE,
            "grid.linewidth": 0.6,
            "grid.alpha": 0.8,
            "lines.linewidth": 1.6,
            "lines.markersize": 4.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def require(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(f"Required frozen input is missing: {path}")
    return path


def save_figure(fig: plt.Figure, stem: str) -> list[Path]:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    pdf = FIGURE_DIR / f"{stem}.pdf"
    png = FIGURE_DIR / f"{stem}.png"
    fig.savefig(
        pdf,
        bbox_inches="tight",
        metadata={"Creator": "GBBRPM paper-output generator", "CreationDate": None},
    )
    fig.savefig(
        png,
        dpi=300,
        bbox_inches="tight",
        metadata={"Software": "GBBRPM paper-output generator"},
    )
    plt.close(fig)
    return [pdf, png]


LATEX_REPLACEMENTS = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: object) -> str:
    text = str(value)
    return "".join(LATEX_REPLACEMENTS.get(char, char) for char in text)


def write_table(
    filename: str,
    *,
    caption: str,
    label: str,
    headers: list[str],
    rows: list[list[object]],
    column_spec: str | None = None,
    wide: bool = False,
    note: str | None = None,
) -> Path:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    environment = "table*" if wide else "table"
    spec = column_spec or ("l" + "r" * (len(headers) - 1))
    lines = [
        "% Auto-generated by scripts/generate_paper_outputs.py; do not edit manually.",
        f"\\begin{{{environment}}}[t]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\small",
        f"\\begin{{tabular}}{{{spec}}}",
        "\\toprule",
        " & ".join(headers) + r" \\",
        "\\midrule",
    ]
    lines.extend(" & ".join(latex_escape(value) for value in row) + r" \\" for row in rows)
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    if note:
        lines.append(f"\\vspace{{2pt}}\\parbox{{0.96\\linewidth}}{{\\footnotesize {note}}}")
    lines.extend([f"\\end{{{environment}}}", ""])
    path = TABLE_DIR / filename
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return path


def layer1_outputs() -> tuple[list[Path], dict]:
    """Generate the data-derived Layer 1 figures used in Chapter 4.

    The publication layer reads committed experiment results only. It does not
    rerun the evaluator, robustness trials, diagnostics, or timing benchmark.
    """

    nodes = pd.read_csv(
        require(ROOT / "data" / "historical" / "validation_reconstructed_nodes.csv")
    )
    core = pd.read_csv(require(ROOT / "results" / "core_scenarios.csv"))
    reconvergence = pd.read_csv(require(ROOT / "results" / "reconvergence_summary.csv"))
    scalability = pd.read_csv(require(ROOT / "results" / "scalability.csv"))

    figures: list[Path] = []
    outlet_nodes: dict[str, str] = {}
    outlet_risks: dict[str, float] = {}

    for network in NETWORKS:
        network_nodes = nodes.loc[nodes["Network"] == network]
        outlet_rows = network_nodes.loc[network_nodes["Outlet"].astype(bool), "Node"]
        if len(outlet_rows) != 1:
            raise ValueError(
                f"Expected exactly one declared outlet for {network}; found {len(outlet_rows)}"
            )
        outlet = str(outlet_rows.iloc[0])
        risk = pd.read_csv(
            require(ROOT / "results" / f"{network}_baseline_node_risk.csv")
        )
        outlet_match = risk.loc[risk["node"].astype(str) == outlet, "R"]
        if len(outlet_match) != 1:
            raise ValueError(
                f"Expected one baseline risk for outlet {outlet} in {network}; "
                f"found {len(outlet_match)}"
            )
        outlet_nodes[network] = outlet
        outlet_risks[network] = float(outlet_match.iloc[0])

    fig, ax = plt.subplots(figsize=(7.16, 3.15))
    bars = ax.bar(
        NETWORKS,
        [outlet_risks[network] for network in NETWORKS],
        color=[NETWORK_COLORS[network] for network in NETWORKS],
        width=0.64,
    )
    ax.set(xlabel="Controlled network", ylabel="Outlet risk index", ylim=(0, 0.80))
    ax.grid(axis="y")
    ax.set_axisbelow(True)
    ax.bar_label(bars, fmt="%.4f", padding=2, fontsize=7)
    figures += save_figure(fig, "fig_layer1_baseline_outlet_risk")

    severity = core.loc[core["scenario_family"] == "severity"].copy()
    severity["parameter"] = pd.to_numeric(severity["parameter"])
    fig, ax = plt.subplots(figsize=(7.16, 3.25))
    for network in NETWORKS:
        rows = severity.loc[severity["network"] == network].sort_values("parameter")
        ax.plot(
            rows["parameter"],
            rows["outlet_risk"],
            label=network,
            color=NETWORK_COLORS[network],
            marker=NETWORK_MARKERS[network],
        )
    ax.set(
        xlabel=r"Source disturbance severity $B$",
        ylabel="Outlet risk index",
        ylim=(0, 0.80),
    )
    ax.set_xticks([0.25, 0.50, 0.75, 1.00])
    ax.grid(axis="y")
    ax.legend(frameon=False, ncol=5, loc="upper left")
    figures += save_figure(fig, "fig_layer1_source_severity")

    lc_stress = core.loc[core["scenario_family"] == "lc_stress"].copy()
    lc_stress["parameter"] = pd.to_numeric(lc_stress["parameter"])
    fig, ax = plt.subplots(figsize=(7.16, 3.25))
    for network in NETWORKS:
        rows = lc_stress.loc[lc_stress["network"] == network].sort_values("parameter")
        ax.plot(
            rows["parameter"],
            rows["outlet_risk"],
            label=network,
            color=NETWORK_COLORS[network],
            marker=NETWORK_MARKERS[network],
        )
    ax.set(
        xlabel=r"Load scale applied before $S=\min(1,L/C)$",
        ylabel="Outlet risk index",
        ylim=(0, 1.05),
    )
    ax.set_xticks([0.50, 0.75, 1.00, 1.25, 1.50])
    ax.grid(axis="y")
    ax.legend(frameon=False, ncol=5, loc="upper left")
    figures += save_figure(fig, "fig_layer1_lc_stress")

    locations = core.loc[core["scenario_family"] == "blockage_location"].copy()
    fig = plt.figure(figsize=(7.16, 4.65))
    grid = fig.add_gridspec(2, 3)
    axes = [
        fig.add_subplot(grid[0, 0]),
        fig.add_subplot(grid[0, 1]),
        fig.add_subplot(grid[0, 2]),
        fig.add_subplot(grid[1, 0]),
        fig.add_subplot(grid[1, 1:]),
    ]
    for ax, network in zip(axes, NETWORKS):
        rows = locations.loc[locations["network"] == network]
        positions = np.arange(len(rows))
        ax.bar(
            positions,
            rows["outlet_risk"],
            color=NETWORK_COLORS[network],
            width=0.68,
        )
        ax.set_title(network, fontweight="bold")
        ax.set_xticks(positions, rows["location"].astype(str))
        ax.set_ylim(0, 0.80)
        ax.grid(axis="y")
        ax.set_axisbelow(True)
    axes[0].set_ylabel("Outlet risk index")
    axes[3].set_ylabel("Outlet risk index")
    axes[3].set_xlabel("Tested disturbance location")
    axes[4].set_xlabel("Tested disturbance location")
    figures += save_figure(fig, "fig_layer1_disturbance_location")

    combinations = core.loc[core["scenario_family"] == "source_combination"].copy()
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 3.25), sharey=True)
    for ax, network in zip(axes, ["N3", "N5"]):
        rows = combinations.loc[combinations["network"] == network]
        positions = np.arange(len(rows))
        bars = ax.bar(
            positions,
            rows["outlet_risk"],
            color=NETWORK_COLORS[network],
            width=0.66,
        )
        ax.set_title(network, fontweight="bold")
        ax.set_xticks(positions, rows["parameter"].astype(str))
        if network == "N5":
            ax.tick_params(axis="x", labelrotation=32)
            for label in ax.get_xticklabels():
                label.set_horizontalalignment("right")
        ax.set_xlabel("Active source configuration")
        ax.set_ylim(0, 0.80)
        ax.grid(axis="y")
        ax.set_axisbelow(True)
        ax.bar_label(bars, fmt="%.4f", padding=2, fontsize=6.5)
    axes[0].set_ylabel("Outlet risk index")
    figures += save_figure(fig, "fig_layer1_source_combinations")

    reconvergence = reconvergence.set_index("network").loc[["N3", "N4", "N5"]].reset_index()
    positions = np.arange(len(reconvergence))
    width = 0.34
    fig, ax = plt.subplots(figsize=(7.16, 3.15))
    outlet_bars = ax.bar(
        positions - width / 2,
        reconvergence["outlet_oi"],
        width,
        color=BLUE,
        label="Outlet overlap inflation",
    )
    maximum_bars = ax.bar(
        positions + width / 2,
        reconvergence["maximum_oi"],
        width,
        color=AMBER,
        label="Maximum node-level overlap inflation",
    )
    ax.set_xticks(positions, reconvergence["network"])
    ax.set(xlabel="Controlled network", ylabel="Overlap inflation index", ylim=(0, 0.50))
    ax.grid(axis="y")
    ax.set_axisbelow(True)
    ax.legend(frameon=False, loc="upper left")
    ax.bar_label(outlet_bars, fmt="%.4f", padding=2, fontsize=7)
    ax.bar_label(maximum_bars, fmt="%.4f", padding=2, fontsize=7)
    figures += save_figure(fig, "fig_layer1_reconvergence")

    lower = scalability["median_ms"] - scalability["q25_ms"]
    upper = scalability["q75_ms"] - scalability["median_ms"]
    fig, ax = plt.subplots(figsize=(7.16, 3.15))
    ax.errorbar(
        scalability["nodes"],
        scalability["median_ms"],
        yerr=[lower, upper],
        color=BLUE,
        marker="o",
        capsize=3,
        label="Median with interquartile range",
    )
    ax.set_xscale("log")
    ax.set_xticks(scalability["nodes"], scalability["nodes"].astype(str))
    ax.set(xlabel=r"Number of nodes $|V|$", ylabel="Runtime (ms)")
    ax.grid(axis="y")
    ax.legend(frameon=False, loc="upper left")
    figures += save_figure(fig, "fig_layer1_scalability")

    family_counts = {
        str(family): int(count)
        for family, count in core.groupby("scenario_family").size().items()
    }
    stats = {
        "networks": NETWORKS,
        "outlets": outlet_nodes,
        "baseline_outlet_risk": {
            network: outlet_risks[network] for network in NETWORKS
        },
        "scenario_family_counts": family_counts,
        "scenario_runs": int(len(core)),
        "historical_scenario_runs": int(
            len(core.loc[core["scenario_family"] != "transmission"])
        ),
    }
    return figures, stats


def software_outputs() -> tuple[list[Path], list[Path], dict]:
    case = ROOT / "data" / "software" / "express_4.18.2"
    results = ROOT / "results" / "software" / "express_4.18.2"
    nodes = pd.read_csv(require(case / "nodes.csv"))
    edges = pd.read_csv(require(case / "edges.csv"))
    risk = pd.read_csv(require(results / "risk_by_tau.csv"))
    summary = pd.read_csv(require(results / "summary_by_tau.csv"))
    stability = pd.read_csv(require(results / "ranking_stability.csv"))
    manifest = json.loads(require(case / "manifest.json").read_text(encoding="utf-8"))

    figures: list[Path] = []
    tables: list[Path] = []

    express_id = "npm:express@4.18.2"
    body_id = "npm:body-parser@1.20.1"
    express = risk.loc[risk["node"] == express_id, ["tau", "R"]].sort_values("tau")
    body = risk.loc[risk["node"] == body_id, ["tau", "R"]].sort_values("tau")
    fig, ax = plt.subplots(figsize=(3.5, 2.45))
    ax.plot(express["tau"], express["R"], marker="o", color=BLUE, label="Express root")
    ax.plot(body["tau"], body["R"], marker="s", color=RED, label="body-parser")
    ax.plot(summary["tau"], summary["max_risk"], linestyle="--", color=NAVY, label="Network maximum")
    ax.set(xlabel=r"Transmission coefficient $\tau$", ylabel="Modeled risk index", xlim=(-0.02, 1.02), ylim=(0, 1.03))
    ax.set_xticks(summary["tau"])
    ax.grid(axis="y")
    ax.legend(frameon=False, loc="lower right")
    figures += save_figure(fig, "fig_software_tau_sensitivity")

    vulnerable = nodes.loc[nodes["B"] > 0].copy()
    vulnerable_ids = set(vulnerable["node"])
    vulnerable_edges = edges.loc[
        edges["source"].isin(vulnerable_ids) & edges["target"].isin(vulnerable_ids)
    ]
    graph = nx.from_pandas_edgelist(
        vulnerable_edges, "source", "target", create_using=nx.DiGraph
    )
    graph.add_nodes_from(vulnerable_ids)
    package_to_node = vulnerable.set_index("package")["node"].to_dict()
    pos = {
        package_to_node["express"]: (2.6, 0.0),
        package_to_node["body-parser"]: (1.05, -0.85),
        package_to_node["serve-static"]: (1.05, 0.85),
        package_to_node["qs"]: (-0.35, -0.85),
        package_to_node["send"]: (-0.35, 0.85),
        package_to_node["cookie"]: (0.55, 1.75),
        package_to_node["path-to-regexp"]: (0.55, -1.75),
    }
    severity_colors = {"HIGH": RED, "MODERATE": AMBER, "LOW": BLUE}
    node_colors = [
        severity_colors.get(
            str(vulnerable.set_index("node").loc[node, "max_severity"]), SLATE
        )
        for node in graph.nodes
    ]
    sizes = [1050 if node == express_id else 760 for node in graph.nodes]
    display_package = {
        "path-to-regexp": "path-to-\nregexp",
        "body-parser": "body-\nparser",
        "serve-static": "serve-\nstatic",
    }
    labels = {
        row.node: f"{display_package.get(row.package, row.package)}\n{row.version}"
        for row in vulnerable.itertuples(index=False)
    }
    fig, ax = plt.subplots(figsize=(7.16, 3.85))
    nx.draw_networkx_edges(
        graph,
        pos,
        ax=ax,
        edge_color=SLATE,
        width=1.1,
        alpha=0.75,
        arrows=True,
        arrowstyle="-|>",
        arrowsize=16,
        min_source_margin=18,
        min_target_margin=24,
        connectionstyle="arc3,rad=0.05",
    )
    nx.draw_networkx_nodes(
        graph,
        pos,
        ax=ax,
        node_color=node_colors,
        node_size=sizes,
        edgecolors=NAVY,
        linewidths=[1.8 if node == express_id else 0.9 for node in graph.nodes],
    )
    nx.draw_networkx_labels(graph, pos, labels=labels, ax=ax, font_size=6.7, font_color="white")
    ax.legend(
        handles=[
            Patch(facecolor=RED, edgecolor=NAVY, label="High local severity"),
            Patch(facecolor=AMBER, edgecolor=NAVY, label="Moderate local severity"),
            Patch(facecolor=BLUE, edgecolor=NAVY, label="Low local severity"),
            Line2D([0], [0], color=SLATE, marker=r"$\rightarrow$", markersize=10, linewidth=0, label="Dependency to dependent"),
        ],
        frameon=False,
        ncol=4,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.05),
    )
    ax.set_xlim(-0.9, 3.15)
    ax.set_ylim(-2.35, 2.35)
    ax.set_axis_off()
    figures += save_figure(fig, "fig_software_vulnerable_subgraph")

    vulnerable_rows = []
    for row in vulnerable.sort_values(["B", "package"], ascending=[False, True]).itertuples(index=False):
        vulnerable_rows.append(
            [row.package, row.version, row.relation_to_root, row.max_severity.title(), f"{row.B:.2f}", row.advisory_count]
        )
    tables.append(
        write_table(
            "table_software_vulnerabilities.tex",
            caption="Evidence-backed local disturbances in the Express dependency case.",
            label="tab:software-vulnerabilities",
            headers=["Package", "Version", "Relation", "Severity", "$B_i$", "Advisories"],
            rows=vulnerable_rows,
            column_spec="llllrr",
            wide=True,
        )
    )

    sensitivity_rows = []
    stability_lookup = stability.set_index("tau")
    express_lookup = express.set_index("tau")
    for row in summary.itertuples(index=False):
        tau_risk = risk.loc[(risk["tau"] == row.tau) & (risk["node"] == express_id)].iloc[0]
        sensitivity_rows.append(
            [
                f"{row.tau:.2f}",
                f"{express_lookup.loc[row.tau, 'R']:.4f}",
                int(tau_risk["rank"]),
                f"{row.max_risk:.4f}",
                f"{stability_lookup.loc[row.tau, 'spearman_vs_reference']:.4f}",
                f"{stability_lookup.loc[row.tau, 'top_20pct_jaccard_vs_reference']:.4f}",
            ]
        )
    tables.append(
        write_table(
            "table_software_sensitivity.tex",
            caption="Software-domain transmission sensitivity and ranking stability.",
            label="tab:software-sensitivity",
            headers=["$\\tau$", "Express $R$", "Rank", "Maximum $R$", "Spearman", "Top-20\\% Jaccard"],
            rows=sensitivity_rows,
            column_spec="rrrrrr",
            wide=True,
            note="Spearman and Jaccard are calculated against the complete ranking at $\\tau=1$.",
        )
    )

    stats = {
        "nodes": int(len(nodes)),
        "edges": int(len(edges)),
        "vulnerable_nodes": int((nodes["B"] > 0).sum()),
        "advisory_matches": int(nodes["advisory_count"].sum()),
        "manifest": manifest,
    }
    return figures, tables, stats


def electrical_outputs() -> tuple[list[Path], list[Path], dict]:
    case = ROOT / "data" / "electrical" / "socal28_sample"
    baseline_dir = ROOT / "results" / "electrical" / "socal28_sample"
    nodes = pd.read_csv(require(case / "nodes.csv"))
    edges = pd.read_csv(require(case / "active_edges.csv"))
    mapping = pd.read_csv(require(case / "meter_mapping.csv"))
    windows = pd.read_csv(require(case / "event_request_windows.csv"))
    topology_manifest = json.loads(require(case / "manifest.json").read_text(encoding="utf-8"))
    baseline = pd.read_csv(require(baseline_dir / "baseline_channel_summary.csv"))
    baseline_manifest = json.loads(
        require(baseline_dir / "baseline_manifest.json").read_text(encoding="utf-8")
    )

    figures: list[Path] = []
    tables: list[Path] = []

    graph = nx.from_pandas_edgelist(edges, "source", "target", create_using=nx.DiGraph)
    graph.add_nodes_from(nodes["node"])
    position = nx.spring_layout(graph, seed=41, k=0.22, iterations=350)
    measured_buses = set(
        mapping.loc[
            mapping["voltage_response_eligible"].fillna(False).astype(bool),
            "base_element",
        ].dropna()
    )
    isolated = set(nx.isolates(graph))
    ordinary = [node for node in graph if node not in measured_buses and node not in isolated]
    measured = [node for node in graph if node in measured_buses]
    isolated_nodes = [node for node in graph if node in isolated]
    fig, ax = plt.subplots(figsize=(7.16, 4.25))
    nx.draw_networkx_edges(
        graph,
        position,
        ax=ax,
        arrows=True,
        arrowstyle="-|>",
        arrowsize=4,
        width=0.45,
        alpha=0.48,
        edge_color=SLATE,
    )
    nx.draw_networkx_nodes(graph, position, nodelist=ordinary, node_size=13, node_color=LIGHT, edgecolors=SLATE, linewidths=0.25, ax=ax)
    nx.draw_networkx_nodes(graph, position, nodelist=measured, node_size=34, node_color=AMBER, edgecolors=NAVY, linewidths=0.5, ax=ax)
    nx.draw_networkx_nodes(graph, position, nodelist=isolated_nodes, node_size=22, node_color="white", edgecolors=SLATE, linewidths=0.7, ax=ax)
    ax.legend(
        handles=[
            Line2D([0], [0], marker="o", color="none", markerfacecolor=LIGHT, markeredgecolor=SLATE, markersize=5, label="Bus"),
            Line2D([0], [0], marker="o", color="none", markerfacecolor=AMBER, markeredgecolor=NAVY, markersize=6, label="Voltage-instrumented bus"),
            Line2D([0], [0], marker="o", color="none", markerfacecolor="white", markeredgecolor=SLATE, markersize=5, label="Isolated bus record"),
        ],
        frameon=False,
        ncol=3,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.04),
    )
    ax.set_axis_off()
    figures += save_figure(fig, "fig_electrical_topology_overview")

    mapped = baseline.loc[baseline["measurement_kind"] != "unmapped"].copy()
    grouped_rows = []
    for meter, group in mapped.groupby("meter"):
        expected = int(group["expected_timestamp_count"].sum())
        missing = int(group["missing_timestamp_count"].sum())
        coverage = 100.0 * (expected - missing) / expected if expected else 0.0
        grouped_rows.append(
            {
                "meter": meter,
                "coverage": coverage,
                "populated": int((group["data_status"] == "populated").sum()),
                "channels": int(len(group)),
            }
        )
    coverage = pd.DataFrame(grouped_rows)
    coverage["meter_number"] = coverage["meter"].str.extract(r"(\d+)").astype(int)
    coverage = coverage.sort_values("meter_number", ascending=False)
    colors = [LIGHT if value == 0 else GREEN if value >= 99 else AMBER for value in coverage["coverage"]]
    fig, ax = plt.subplots(figsize=(3.5, 4.6))
    bars = ax.barh(coverage["meter"], coverage["coverage"], color=colors, edgecolor="white", height=0.72)
    ax.axvline(99, color=SLATE, linewidth=0.8, linestyle="--")
    ax.set(xlabel="Timestamp coverage (%)", xlim=(0, 104))
    ax.grid(axis="x")
    ax.set_axisbelow(True)
    for bar, value in zip(bars, coverage["coverage"]):
        label = "No data" if value == 0 else f"{value:.1f}"
        ax.text(min(value + 1.0, 100.5), bar.get_y() + bar.get_height() / 2, label, va="center", fontsize=6.5, color=NAVY)
    coverage_handles = [Patch(facecolor=GREEN, label=r"$\geq 99\%$")]
    if ((coverage["coverage"] > 0) & (coverage["coverage"] < 99)).any():
        coverage_handles.append(Patch(facecolor=AMBER, label=r"$<99\%$"))
    coverage_handles.append(Patch(facecolor=LIGHT, label="Empty meter"))
    ax.legend(
        handles=coverage_handles,
        frameon=False,
        ncol=3,
        loc="lower center",
        bbox_to_anchor=(0.5, 1.0),
    )
    figures += save_figure(fig, "fig_electrical_baseline_coverage")

    eligible = baseline.loc[baseline["per_unit_status"] == "available", "mean_per_unit"]
    topology_rows = [
        ["Bus records", topology_manifest["bus_records"]],
        ["Active directed connections", topology_manifest["active_edge_records"]],
        ["Weak components (all buses)", topology_manifest["all_bus_weak_components"]],
        ["Documented status transitions", topology_manifest["documented_status_transition_count"]],
        ["Baseline channel files", baseline_manifest["summarized_file_count"]],
        ["Mapped channel files", baseline_manifest["mapped_file_count"]],
        ["Populated / empty files", f"{baseline_manifest['populated_file_count']} / {baseline_manifest['empty_file_count']}"],
        ["Overall timestamp coverage", f"{100 * baseline_manifest['timestamp_coverage_fraction']:.2f}%"],
        ["Usable voltage channels", int(len(eligible))],
        ["Mean-voltage range", f"{eligible.min():.4f}--{eligible.max():.4f} p.u."],
    ]
    tables.append(
        write_table(
            "table_electrical_baseline.tex",
            caption="Electrical topology and baseline-measurement summary.",
            label="tab:electrical-baseline",
            headers=["Measure", "Value"],
            rows=topology_rows,
            column_spec="lr",
            note="The baseline covers normal operation from November 14--15, 2024 and is not event-response validation.",
        )
    )

    quality_rows = []
    for kind, group in baseline.groupby("measurement_kind", sort=True):
        quality_rows.append(
            [
                kind.replace("_", " ").title(),
                len(group),
                int((group["data_status"] == "populated").sum()),
                int((group["data_status"] == "empty").sum()),
                int(group["missing_timestamp_count"].sum()),
            ]
        )
    tables.append(
        write_table(
            "table_electrical_data_quality.tex",
            caption="Electrical baseline channel availability and timestamp gaps.",
            label="tab:electrical-quality",
            headers=["Measurement kind", "Files", "Populated", "Empty", "Missing intervals"],
            rows=quality_rows,
            column_spec="lrrrr",
            wide=True,
            note="Missing intervals are counted at each populated channel's inferred one-second cadence; empty channels are reported separately.",
        )
    )

    windows["start_time"] = pd.to_datetime(windows["start_time"])
    november = windows.loc[windows["start_time"].dt.strftime("%Y-%m-%d") == "2024-11-13"]
    event_rows = []
    for row in november.itertuples(index=False):
        event_rows.append(
            [
                row.event_group.split("_", 1)[0],
                row.start_time.strftime("%H:%M:%S"),
                row.operation_count,
                str(row.event_kinds).replace("|", ", "),
                pd.Timestamp(row.recommended_query_start).strftime("%H:%M:%S"),
                pd.Timestamp(row.recommended_query_end).strftime("%H:%M:%S"),
            ]
        )
    tables.append(
        write_table(
            "table_electrical_event_windows.tex",
            caption="Requested November 13, 2024 electrical event windows.",
            label="tab:electrical-event-windows",
            headers=["Group", "Event start", "Operations", "Kinds", "Query start", "Query end"],
            rows=event_rows,
            column_spec="llrlll",
            wide=True,
            note="Event-centered measurements remain pending provider authorization; these windows do not imply completed outcome validation.",
        )
    )

    stats = {
        "buses": int(len(nodes)),
        "active_edges": int(len(edges)),
        "baseline_files": int(len(baseline)),
        "mapped_files": int((baseline["measurement_kind"] != "unmapped").sum()),
        "usable_voltage_channels": int(len(eligible)),
        "topology_manifest": topology_manifest,
        "baseline_manifest": baseline_manifest,
    }
    return figures, tables, stats


def drainage_outputs() -> tuple[list[Path], list[Path], dict]:
    network_summary = pd.read_csv(
        require(ROOT / "data" / "recovered_candidate" / "N1-N5_network_summary.csv")
    )
    robustness = pd.read_csv(require(ROOT / "results" / "N5_robustness_summary.csv"))
    swmm = pd.read_csv(
        require(ROOT / "data" / "swmm" / "extracted" / "swmm_comparison_summary.csv")
    ).iloc[0]

    figures: list[Path] = []
    tables: list[Path] = []

    x = robustness["pct"] * 100
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.55))
    axes[0].errorbar(
        x,
        robustness["mean_spearman"],
        yerr=[
            robustness["mean_spearman"] - robustness["p05_spearman"],
            robustness["p95_spearman"] - robustness["mean_spearman"],
        ],
        marker="o",
        capsize=3,
        color=BLUE,
    )
    axes[0].set(xlabel="Susceptibility perturbation (%)", ylabel="Spearman rank correlation", ylim=(0, 1.02))
    axes[0].set_xticks(x)
    axes[0].grid(axis="y")
    axes[1].plot(x, robustness["mean_top_20pct_jaccard"], marker="s", color=AMBER)
    axes[1].set(xlabel="Susceptibility perturbation (%)", ylabel="Top-20% Jaccard", ylim=(0, 1.02))
    axes[1].set_xticks(x)
    axes[1].grid(axis="y")
    figures += save_figure(fig, "fig_drainage_robustness")

    metric_labels = ["Depth\nSpearman", "Flooding\nSpearman", "Depth\nJaccard", "Flooding\nJaccard"]
    metric_values = [
        swmm["mean_depth_spearman"],
        swmm["mean_flooding_spearman"],
        swmm["mean_depth_top20pct_jaccard"],
        swmm["mean_flooding_top20pct_jaccard"],
    ]
    fig, ax = plt.subplots(figsize=(3.5, 2.55))
    bars = ax.bar(metric_labels, metric_values, color=[BLUE, BLUE, AMBER, AMBER], width=0.68)
    ax.axhline(0, color=NAVY, linewidth=0.7)
    ax.set(ylabel="Agreement metric", ylim=(-0.6, 0.25))
    ax.grid(axis="y")
    ax.set_axisbelow(True)
    for bar, value in zip(bars, metric_values):
        offset = 0.025 if value >= 0 else -0.04
        va = "bottom" if value >= 0 else "top"
        ax.text(bar.get_x() + bar.get_width() / 2, value + offset, f"{value:.3f}", ha="center", va=va, fontsize=7)
    figures += save_figure(fig, "fig_drainage_swmm_alignment")

    network_rows = []
    for row in network_summary.itertuples(index=False):
        network_rows.append(
            [
                str(row.Network).split("_", 1)[0],
                row.Nodes,
                row.Edges,
                row.Sources,
                f"{row.Mean_S:.3f}",
                row.Purpose,
            ]
        )
    tables.append(
        write_table(
            "table_drainage_networks.tex",
            caption="Synthetic drainage-network evaluation set.",
            label="tab:drainage-networks",
            headers=["Network", "Nodes", "Edges", "Sources", "Mean $S$", "Primary purpose"],
            rows=network_rows,
            column_spec=r"lrrrrp{7.0cm}",
            wide=True,
        )
    )

    validation_rows = [
        ["Mean depth", f"{swmm['mean_depth_spearman']:.3f}", f"{swmm['mean_depth_top20pct_jaccard']:.3f}", f"{100 * swmm['mean_depth_outside_scope_share']:.1f}%"],
        ["Flooding", f"{swmm['mean_flooding_spearman']:.3f}", f"{swmm['mean_flooding_top20pct_jaccard']:.3f}", f"{100 * swmm['mean_flooding_outside_scope_share']:.1f}%"],
    ]
    tables.append(
        write_table(
            "table_drainage_swmm.tex",
            caption="GBBRPM and SWMM ranking comparison across 12 blockage scenarios.",
            label="tab:drainage-swmm",
            headers=["Hydraulic outcome", "Mean Spearman", "Top-20\\% Jaccard", "Outside-scope share"],
            rows=validation_rows,
            column_spec="lrrr",
            wide=True,
            note="Negative rank correlations and low priority-set overlap are reported without reinterpreting the modeled risk index as a hydraulic predictor.",
        )
    )

    stats = {
        "synthetic_networks": int(len(network_summary)),
        "swmm_scenarios": int(swmm["scenarios"]),
    }
    return figures, tables, stats


def cross_domain_table(drainage: dict, software: dict, electrical: dict) -> Path:
    rows = [
        [
            "Drainage",
            f"{drainage['synthetic_networks']} synthetic DAGs; {drainage['swmm_scenarios']} SWMM scenarios",
            "Behavioral tests and hydraulic-reference comparison",
            "Completed",
        ],
        [
            "Software",
            f"{software['nodes']} packages; {software['edges']} dependency edges; {software['vulnerable_nodes']} vulnerable versions",
            "Real-topology structural applicability and sensitivity",
            "Completed",
        ],
        [
            "Electrical",
            f"{electrical['buses']} buses; {electrical['active_edges']} active connections; {electrical['baseline_files']} baseline files",
            "Real-topology and baseline importer verification",
            "Event validation pending",
        ],
    ]
    return write_table(
        "table_cross_domain_evidence.tex",
        caption="Evidence roles of the three evaluated domains.",
        label="tab:cross-domain-evidence",
        headers=["Domain", "Instantiated data", "Evidentiary role", "Status"],
        rows=rows,
        column_spec=r"lp{5.0cm}p{6.0cm}l",
        wide=True,
        note="The three cases test different claims; structural applicability is not labeled as empirical prediction validation.",
    )


def main() -> None:
    configure_style()
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    figure_paths: list[Path] = []
    table_paths: list[Path] = []
    layer1_figures, layer1_stats = layer1_outputs()
    drainage_figures, drainage_tables, drainage_stats = drainage_outputs()
    software_figures, software_tables, software_stats = software_outputs()
    electrical_figures, electrical_tables, electrical_stats = electrical_outputs()
    figure_paths += (
        layer1_figures + drainage_figures + software_figures + electrical_figures
    )
    table_paths += drainage_tables + software_tables + electrical_tables
    table_paths.append(cross_domain_table(drainage_stats, software_stats, electrical_stats))

    inputs = [
        ROOT / "data" / "historical" / "validation_reconstructed_nodes.csv",
        ROOT / "results" / "core_scenarios.csv",
        *[
            ROOT / "results" / f"{network}_baseline_node_risk.csv"
            for network in NETWORKS
        ],
        ROOT / "data" / "recovered_candidate" / "N1-N5_network_summary.csv",
        ROOT / "results" / "N5_robustness_summary.csv",
        ROOT / "results" / "reconvergence_summary.csv",
        ROOT / "results" / "scalability.csv",
        ROOT / "data" / "swmm" / "extracted" / "swmm_comparison_summary.csv",
        ROOT / "data" / "software" / "express_4.18.2" / "nodes.csv",
        ROOT / "data" / "software" / "express_4.18.2" / "edges.csv",
        ROOT / "results" / "software" / "express_4.18.2" / "risk_by_tau.csv",
        ROOT / "results" / "software" / "express_4.18.2" / "summary_by_tau.csv",
        ROOT / "results" / "software" / "express_4.18.2" / "ranking_stability.csv",
        ROOT / "data" / "electrical" / "socal28_sample" / "nodes.csv",
        ROOT / "data" / "electrical" / "socal28_sample" / "active_edges.csv",
        ROOT / "data" / "electrical" / "socal28_sample" / "meter_mapping.csv",
        ROOT / "data" / "electrical" / "socal28_sample" / "event_request_windows.csv",
        ROOT / "results" / "electrical" / "socal28_sample" / "baseline_channel_summary.csv",
        ROOT / "results" / "electrical" / "socal28_sample" / "baseline_manifest.json",
    ]
    manifest = {
        "generator": "scripts/generate_paper_outputs.py",
        "deterministic_layout_seed": 41,
        "input_sha256": {
            str(path.relative_to(ROOT)): sha256(require(path)) for path in inputs
        },
        "layer1_paper_alignment": layer1_stats,
        "figures": [
            {"path": str(path.relative_to(ROOT)), "sha256": sha256(path)}
            for path in sorted(figure_paths)
        ],
        "tables": [
            {"path": str(path.relative_to(ROOT)), "sha256": sha256(path)}
            for path in sorted(table_paths)
        ],
        "interpretation_boundary": (
            "Drainage includes behavioral and SWMM-reference evidence; software "
            "supports structural cross-domain applicability; electrical supports "
            "topology and baseline preprocessing while event validation remains pending."
        ),
    }
    manifest_path = OUTPUT_ROOT / "paper_outputs_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"Generated {len(figure_paths)} figure files, {len(table_paths)} LaTeX "
        f"tables, and {manifest_path.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
